### PR TITLE
Implement gallop mode in timsort (#49)

### PR DESCRIPTION
**Pull request by liwt31**
This PR implements gallop mode in timsort according to the [CPython code](https://github.com/python/cpython/blob/master/Objects/fileobject.c). Benchmark between this implementation and the original timsort (`otim sort` or `osortertim_sort`) is shown below (array size 1600, averaged over 1000 tests):
```
             tim sort -- stable
            otim sort -- stable
-------
Running tests with random numbers:
-------
sort.h sortertim_sort         - ok,    61202.0 usec
sort.h osortertim_sort        - ok,    50822.0 usec
-------
Running tests with same number:
-------
sort.h sortertim_sort         - ok,      511.0 usec
sort.h osortertim_sort        - ok,      478.0 usec
-------
Running tests with sorted numbers:
-------
sort.h sortertim_sort         - ok,      560.0 usec
sort.h osortertim_sort        - ok,      487.0 usec
-------
Running tests with sorted blocks of length 10:
-------
sort.h sortertim_sort         - ok,    41630.0 usec
sort.h osortertim_sort        - ok,    42016.0 usec
-------
Running tests with sorted blocks of length 100:
-------
sort.h sortertim_sort         - ok,    13310.0 usec
sort.h osortertim_sort        - ok,    14273.0 usec
-------
Running tests with sorted blocks of length 10000:
-------
sort.h sortertim_sort         - ok,      494.0 usec
sort.h osortertim_sort        - ok,      479.0 usec
-------
Running tests with swapped size/2 pairs:
-------
sort.h sortertim_sort         - ok,     1012.0 usec
sort.h osortertim_sort        - ok,     1617.0 usec
-------
Running tests with swapped size/8 pairs:
-------
sort.h sortertim_sort         - ok,      997.0 usec
sort.h osortertim_sort        - ok,     1636.0 usec
```
The overhead is significant for random numbers, while gain from nearly sorted numbers (last 2 tests) is pretty decent.
If the size of the array is multiplied by 10 (to 16000), smaller overhead is expected:
```
             tim sort -- stable
            otim sort -- stable
-------
Running tests with random numbers:
-------
sort.h sortertim_sort         - ok,   618967.0 usec
sort.h osortertim_sort        - ok,   663787.0 usec
-------
Running tests with same number:
-------
sort.h sortertim_sort         - ok,     5541.0 usec
sort.h osortertim_sort        - ok,     5740.0 usec
-------
Running tests with sorted numbers:
-------
sort.h sortertim_sort         - ok,     5491.0 usec
sort.h osortertim_sort        - ok,     5549.0 usec
-------
Running tests with sorted blocks of length 10:
-------
sort.h sortertim_sort         - ok,   645361.0 usec
sort.h osortertim_sort        - ok,   657122.0 usec
-------
Running tests with sorted blocks of length 100:
-------
sort.h sortertim_sort         - ok,   302787.0 usec
sort.h osortertim_sort        - ok,   308961.0 usec
-------
Running tests with sorted blocks of length 10000:
-------
sort.h sortertim_sort         - ok,    18291.0 usec
sort.h osortertim_sort        - ok,    21772.0 usec
-------
Running tests with swapped size/2 pairs:
-------
sort.h sortertim_sort         - ok,     6765.0 usec
sort.h osortertim_sort        - ok,    14864.0 usec
-------
Running tests with swapped size/8 pairs:
-------
sort.h sortertim_sort         - ok,     6765.0 usec
sort.h osortertim_sort        - ok,    14566.0 usec
```
I don't quite understand why with larger array gallop mode enabled timsort performs better even in cases such as random numbers. Maybe some fluctuation in my environment? Still, the gallop mode proves to be a reasonable improvement.

This [cmp.c](https://gist.github.com/liwt31/da9fb67e5c98c60a661ce73f55ff805e) is the benchmark file I used, modified from `stresstest.c`. Put this `sort.h` and the original `sort.h` as `osort.h` in the same directory with `cmp.c` then it's ready to go.

### CODE REVIEW

**Comment by liwt31** [comment]
CI failed - but I can't reproduce the error for now. Might need some time.

**Comment by liwt31** [comment]
A misused `memcpy` instead of `memmove`. Should be solved now.

**Comment by swenson** [comment]
In general this looks good.

The main issue I have is that there are definitely pieces that are copied directly from https://github.com/python/cpython/blob/master/Objects/listobject.c -- that would violate the terms of the PSF license the code falls under.

If possible, could we do a clean room implementation?

**Comment by liwt31** [comment]
I was thinking it's a public algorithm so didn't notice the copyright thing. I'm curious how we can do a clean room implementation, it seems that I, who clearly have read the source code in CPython, can only write some specification and let someone else do the implementation. Is it ok if I implement the algorithm again without any reference to the CPython code?

**Comment by swenson** [comment]
The algorithm is public, but their source code is under their license, and this contains sections copied directly.

I think it would be fine if you re-implemented it based on knowledge of the algorithm, but without directly copying the code.

**Comment by liwt31** [comment]
Closing this because a clean room implementation literally means starting from the beginning and a new PR is submitted.

**Pull request closed without merging**
